import type { RouteDay, RouteStop } from './route-data';

const tokyoHotel = 'Hotel Horidome Villa Tokyo';
const warner = 'Warner Bros. Studio Tour Tokyo The Making of Harry Potter';
const stop = (
  time: string,
  title: string,
  query: string,
  detail: string,
  leg: string,
  mode: RouteStop['mode'],
  kind: RouteStop['kind'],
  duration: string,
  purchaseIds?: string[],
  source?: RouteStop['source'],
): RouteStop => ({
  time,
  title,
  query,
  detail,
  leg,
  mode,
  kind,
  duration,
  purchaseIds,
  source,
});

export function updateTokyoDay(day: RouteDay): RouteDay {
  if (day.date === '2026-11-08') {
    return {
      ...day,
      title: 'Warner Bros. — мир Гарри Поттера и вечер в Синдзюку',
      origin: tokyoHotel,
      pace: 'Полдня в студии · спокойный вечер',
      walk: undefined,
      note: 'Warner Bros. поставлен на 8 ноября: на 9–12 ноября объявлено закрытие. На 8 ноября 10:00 проверены два взрослых билета за ¥13 200 с налогом (9 сентября 2026); слот ещё не забронирован. Это последний день программы Dark Arts Halloween. Мэйдзи и Сибуя перенесены на 9 ноября. Проездной Tokyo Subway на 72 часа активировать утром 7 ноября: поездки по Toei в этот день войдут в уже учтённый транспортный бюджет.',
      stops: [
        stop(
          '08:00–09:15',
          'Доехать к Warner Bros. через Синдзюку',
          'Toshimaen Station Toei Oedo Line Tokyo',
          'От Horidome пешком до Bakuro-yokoyama, затем Toei Shinjuku Line до Shinjuku и Toei Oedo Line в сторону Hikarigaoka до Toshimaen. От станции до студии около 2 минут пешком. Заложен запас на переход между линиями и поиск входа. Этот маршрут покрывает Tokyo Subway Ticket; поезда Seibu и JR в него не входят.',
          'Отель → Bakuro-yokoyama → Shinjuku → Toshimaen',
          'transit',
          'travel',
          '1 ч 15 мин с запасом',
          ['t-tokyo-local'],
          {
            label: 'Warner Bros.: дорога на поезде',
            url: 'https://www.wbstudiotour.jp/en/plan-your-visit/location/',
          },
        ),
        stop(
          '09:15–10:00',
          'Вход, контроль и подготовка к туру',
          warner,
          'Целевой билет на 10:00. В здание пускают за час до указанного слота: спокойно пройти проверку сумок и туалет. Чемоданы остаются в отеле, поскольку в этот день нет переезда.',
          'От станции: около 2 минут пешком',
          'walking',
          'travel',
          '45 мин',
          undefined,
          {
            label: 'Правила прибытия',
            url: 'https://www.wbstudiotour.jp/en/plan-your-visit/arrival/',
          },
        ),
        stop(
          '10:00–14:30',
          'Warner Bros. Studio Tour Tokyo — Гарри Поттер',
          warner,
          'Большой зал, Хогвартс-экспресс, Запретный лес, Косой переулок и Министерство магии. Отведено 4,5 часа с фотографиями и перерывом на обед. Два стандартных взрослых билета ¥13 200; аудиогид, сувениры, платная съёмка на метле и еда оплачиваются отдельно. Официальная проверка 9 сентября: слот 8 ноября 10:00 доступен, покупка не выполнена.',
          'Внутри студии, самостоятельная прогулка',
          'walking',
          'main',
          '4 ч 30 мин',
          ['p-warner'],
          {
            label: 'Купить стандартные билеты Warner Bros.',
            url: 'https://book.wbstudiotour.com/?event_type_id=30&journey_id=10&language_id=1&site_id=3',
          },
        ),
        stop(
          '14:30–15:15',
          'Вернуться в Синдзюку',
          'Shinjuku Station Toei Oedo Line Tokyo',
          'Вернуться по Oedo Line до Shinjuku. Поезд по официальному ориентиру занимает около 20 минут; остальное время оставлено на подходы и выход со станции.',
          'Toshimaen → Shinjuku по Toei Oedo',
          'transit',
          'travel',
          '45 мин с подходами',
          ['t-tokyo-local'],
        ),
        stop(
          '15:15–18:00',
          'Синдзюку: прогулка и ужин',
          'Shinjuku East Exit Tokyo',
          'Неоновый Синдзюку, магазины у восточного выхода и ранний ужин. Это свободная часть дня: если захочется дольше побыть в студии, сократить её без спешки.',
          'От станции: пешком',
          'walking',
          'rest',
          'До 2 ч 45 мин',
        ),
        stop(
          '18:00–19:00',
          'Вернуться в Horidome Villa',
          tokyoHotel,
          'Toei Shinjuku Line до Bakuro-yokoyama и пешком в отель. Использовать тот же активный 72-часовой проездной.',
          'Синдзюку → Bakuro-yokoyama → отель',
          'transit',
          'rest',
          'До 60 мин',
          ['t-tokyo-local'],
        ),
      ],
    };
  }

  if (day.date === '2026-11-09') {
    return {
      ...day,
      title: 'Мэйдзи, Харадзюку и Сибуя',
      origin: tokyoHotel,
      pace: 'Около 7–9 км пешком · последний полный день',
      note: 'Сибуя перенесена с 8 на 9 ноября, чтобы выделить полдня Warner Bros. Дневной слот Shibuya Sky до 15:00 стоит ¥2 700 на человека; продажи на 9 ноября ожидаются с 26 октября по правилу двух недель. Мэйдзи в ноябре открыт 06:10–16:10, поэтому идём утром.',
      walk: [
        'Meiji-jingumae Station Tokyo',
        'Omotesando Tokyo',
        'Shibuya Scramble Crossing Tokyo',
        'Shibuya Sky Tokyo',
      ],
      stops: [
        stop(
          '08:00–09:00',
          'Дорога к Мэйдзи',
          'Meiji-jingumae Station Tokyo',
          'Пешком до Mitsukoshimae, Ginza Line до Omote-sando, затем Chiyoda Line до Meiji-jingumae. Дальше к южному входу святилища. Линии Tokyo Metro входят в 72-часовой проездной; JR до Harajuku оплачивается отдельно.',
          'От отеля: около 45–60 мин',
          'transit',
          'travel',
          '60 мин',
          ['t-tokyo-local'],
        ),
        stop(
          '09:00–10:30',
          'Мэйдзи-дзингу',
          'Meiji Jingu Tokyo',
          'Лесная дорожка и главное святилище, вход бесплатный. Музей и платный внутренний сад — по желанию вместо части прогулки.',
          'От станции к святилищу: 15–20 мин',
          'walking',
          'main',
          '1 ч 30 мин',
          undefined,
          {
            label: 'Мэйдзи: часы посещения',
            url: 'https://www.meijijingu.or.jp/en/visit/',
          },
        ),
        stop(
          '10:30–12:30',
          'Харадзюку и Омотэсандо',
          'Takeshita Street Harajuku Tokyo',
          'Торговые улицы, архитектура Омотэсандо и обед. До Сибуи продолжить пешком; после 12:30 оставлен час на дорогу и вход в Scramble Square.',
          'От Мэйдзи: около 15–20 мин',
          'walking',
          'main',
          '2 часа',
        ),
        stop(
          '13:30–15:00',
          'Shibuya Sky',
          'Shibuya Sky Tokyo',
          'Целевой слот 13:30–14:00 9 ноября, ещё не бронь. Вход в Scramble Square на 14-м этаже. Дневной тариф ¥5 400 за двоих; перед покупкой сверить доступность выбранной даты.',
          'Харадзюку → Сибуя: 25–40 мин пешком',
          'walking',
          'main',
          '1 ч 30 мин',
          ['p-sky'],
          {
            label: 'Shibuya Sky: билеты',
            url: 'https://www.shibuya-scramble-square.com/sky/ticket/',
          },
        ),
        stop(
          '15:00–17:30',
          'Перекрёсток Сибуя и Hachiko',
          'Shibuya Scramble Crossing Tokyo',
          'Знаменитый перекрёсток, Hachiko, магазины и ранний ужин. Если устали, сократить покупки: вечером нужно упаковать обратный багаж.',
          'У станции Сибуя',
          'walking',
          'main',
          '2 ч 30 мин',
        ),
        stop(
          '17:30–18:30',
          'Вернуться в отель',
          tokyoHotel,
          'Ginza Line до Mitsukoshimae и пешком в Horidome Villa. Проверить, что 72-часовой проездной ещё действует.',
          'Сибуя → Mitsukoshimae → отель',
          'transit',
          'travel',
          'До 60 мин',
          ['t-tokyo-local'],
        ),
        stop(
          '18:30–20:00',
          'Собрать чемоданы',
          tokyoHotel,
          'Проверить обратный багаж, аэропорт и терминал по билету. Завтра — свободное утро и переезд в Нариту.',
          'В отеле',
          'none',
          'rest',
          '1 ч 30 мин',
        ),
      ],
    };
  }

  return day;
}
