export type Purchase = {
  id: string;
  category: 'flight' | 'hotel' | 'transport' | 'place' | 'daily';
  title: string;
  date: string;
  city: string;
  price: number;
  note: string;
  kind: 'quote' | 'tariff' | 'budget';
  link?: string;
  linkLabel?: string;
  extra?: { label: string; url: string };
};
export const groups = [
  { id: 'flight', name: 'Перелёты', label: 'Сначала — билеты между странами' },
  {
    id: 'hotel',
    name: 'Где жить',
    label: 'Отдельный номер на двоих · собственный санузел',
  },
  {
    id: 'transport',
    name: 'Как добраться',
    label: 'Межгород, аэропорты и местные поездки',
  },
  { id: 'place', name: 'Впечатления', label: 'Парки, храмы, океан и онсэн' },
  { id: 'daily', name: 'На каждый день', label: 'Еда и небольшие расходы' },
];
const flight = (from: string, to: string, date: string) =>
  `https://ru.trip.com/flights/showfarefirst?dcity=${from}&acity=${to}&ddate=${date}&triptype=ow&class=y&quantity=2&locale=ru-RU&curr=RUB`;
const hotel = (city: number, id: number, from: string, to: string) =>
  `https://ru.trip.com/hotels/detail/?cityId=${city}&hotelId=${id}&checkIn=${from}&checkOut=${to}&adult=2&crn=1&curr=RUB`;
export const purchases: Purchase[] = [
  {
    id: 'f-moscow',
    category: 'flight',
    title: 'Москва → Наха',
    date: '20–22 октября',
    city: 'Окинава',
    price: 82118,
    kind: 'quote',
    note: '20.10 22:00 SVO → 22.10 19:30 OKA. Через Ханчжоу и Гонконг, 39 ч 30 мин. Самостоятельная пересадка в Гонконге. Обычная ручная кладь на последнем рейсе включена в расчёт; сквозного багажа нет.',
    link: flight('mow', 'oka', '2026-10-20'),
    linkLabel: 'Найти рейс на Trip.com',
  },
  {
    id: 'f-osaka',
    category: 'flight',
    title: 'Наха → Осака · Peach MM212',
    date: '28 октября · 12:20–14:15',
    city: 'Осака',
    price: 10272,
    kind: 'quote',
    note: 'Прямой рейс, аэропорт Кансай T2. Ручная кладь до 7 кг, без сдаваемого багажа. Сумма на двух взрослых.',
    link: flight('oka', 'osa', '2026-10-28'),
    linkLabel: 'Найти рейс на Trip.com',
  },
  {
    id: 'f-home',
    category: 'flight',
    title: 'Токио → Москва · Qatar Airways',
    date: '10–12 ноября',
    city: 'Токио',
    price: 74662,
    kind: 'quote',
    note: '10.11 21:55 NRT → 12.11 07:00 SVO. Пересадка в Дохе 21 ч 20 мин, вся дорога 39 ч 05 мин. Багаж по 25 кг и ручная кладь по 7 кг. Отель в Дохе в бюджет не включён.',
    link: flight('tyo', 'mow', '2026-11-10'),
    linkLabel: 'Найти рейс на Trip.com',
  },
  {
    id: 'h-transit',
    category: 'hotel',
    title: 'Hanting · Hangzhou Xiaoshan Airport',
    date: '21–22 октября · 1 ночь',
    city: 'Пересадка',
    price: 3026.69,
    kind: 'quote',
    note: 'Двухместный номер. Заявлен бесплатный трансфер из/в аэропорт: согласовать время с отелем. Выход в город зависит от условий въезда и решения пограничной службы.',
    link: 'https://ru.trip.com/hotels/hangzhou-hotel-detail-1535526/hanting-hotel/?checkin=2026-10-21&checkout=2026-10-22&adult=2&crn=1&curr=RUB',
    linkLabel: 'Посмотреть номер',
  },
  {
    id: 'h-naha',
    category: 'hotel',
    title: 'Mr.KINJO in MIEGUSUKU',
    date: '22–25 октября · 3 ночи',
    city: 'Наха',
    price: 12097.56,
    kind: 'quote',
    note: '20 м², небольшая двуспальная кровать, свой санузел. До Asahibashi около 1,5 км; до порта дополнительный путь. Стойка до 21:00 — заранее согласовать поздний заезд.',
    link: 'https://ru.trip.com/hotels/naha-hotel-detail-62418188/mrkinjo-in-miegusuku/?checkin=2026-10-22&checkout=2026-10-25&adult=2&crn=1&curr=RUB',
    linkLabel: 'Посмотреть номер',
  },
  {
    id: 'h-onna',
    category: 'hotel',
    title: 'Beach Resort Hotel Kalakaua',
    date: '25–28 октября · 3 ночи',
    city: 'Онна',
    price: 12736.86,
    kind: 'quote',
    note: 'Twin B/C, 18 м², две кровати, свой санузел. Пляж рядом, около 5 минут до остановки Kariyushi Beach. Самостоятельное заселение; хранения чемоданов до/после проживания нет.',
    link: 'https://ru.trip.com/hotels/onna-hotel-detail-39269056/beach-resort-hotel-kalakaua/?checkin=2026-10-25&checkout=2026-10-28&adult=2&crn=1&curr=RUB',
    linkLabel: 'Посмотреть номер',
  },
  {
    id: 'h-osaka',
    category: 'hotel',
    title: 'nippori · апартаменты',
    date: '28 октября — 1 ноября · 4 ночи',
    city: 'Осака',
    price: 9939.34,
    kind: 'quote',
    note: 'Номер для 1–3 человек, 30 м², свой санузел. Тип кроватей назначает объект. Метро Kishinosato 900 м, Tengachaya около 1 км. Самостоятельный заезд; уборка включена, тариф невозвратный.',
    link: hotel(219, 112370196, '2026-10-28', '2026-11-01'),
    linkLabel: 'Посмотреть номер',
  },
  {
    id: 'h-kyoto',
    category: 'hotel',
    title: 'KIORI Exec Gojo',
    date: '1–5 ноября · 4 ночи',
    city: 'Киото',
    price: 25543.99,
    kind: 'quote',
    note: 'Twin, 17–19 м², свой санузел. До метро Gojo около 880 м. Невозвратный тариф. Киото остаётся отдельной остановкой, без ежедневных поездок из Осаки.',
    link: hotel(734, 131589475, '2026-11-01', '2026-11-05'),
    linkLabel: 'Посмотреть номер',
  },
  {
    id: 'h-fuji',
    category: 'hotel',
    title: 'Toyoko Inn Fuji Kawaguchiko Ohashi',
    date: '5–6 ноября · 1 ночь',
    city: 'Фудзи',
    price: 10664.15,
    kind: 'quote',
    note: 'Двухместный номер 12 м², свой санузел, два завтрака включены. Онсэна в отеле нет: Yurari отдельной покупкой ниже.',
    link: 'https://ru.trip.com/hotels/fujikawaguchiko-hotel-detail-29772899/toyoko-inn-fuji-kawaguchiko-ohashi/?checkin=2026-11-05&checkout=2026-11-06&adult=2&crn=1&curr=RUB',
    linkLabel: 'Посмотреть номер',
  },
  {
    id: 'h-tokyo',
    category: 'hotel',
    title: 'Hotel Horidome Villa',
    date: '6–10 ноября · 4 ночи',
    city: 'Токио',
    price: 29722.53,
    kind: 'quote',
    note: 'Semi-double, 11 м², свой санузел. Небольшая кровать на двоих; ширину проверить при выборе. Район Nihombashi, станции Kodemmacho / Ningyocho. Невозвратный тариф.',
    link: hotel(228, 686321, '2026-11-06', '2026-11-10'),
    linkLabel: 'Посмотреть номер',
  },
];
const yen = (amount: number) => Math.round(amount * 0.552789);
const travel = (
  id: string,
  title: string,
  date: string,
  city: string,
  price: number,
  note: string,
  link?: string,
  kind: Purchase['kind'] = 'tariff',
): Purchase => ({
  id,
  category: 'transport',
  title,
  date,
  city,
  price,
  note,
  link,
  kind,
  linkLabel: 'Тарифы и оформление',
});
const place = (
  id: string,
  title: string,
  date: string,
  city: string,
  jpy: number,
  note: string,
  link: string,
  extra?: Purchase['extra'],
): Purchase => ({
  id,
  category: 'place',
  title,
  date,
  city,
  price: yen(jpy),
  note,
  kind: 'tariff',
  link,
  linkLabel: 'Билеты и условия',
  extra,
});
purchases.push(
  travel(
    't-naha',
    'Аэропорт Нахи → город',
    '22 октября',
    'Наха',
    yen(580),
    'Yui Rail до Asahibashi: по ¥290. До отеля ещё около 1,5 км; такси оплачивается из резерва.',
    'https://www.yui-rail.co.jp/',
  ),
  travel(
    't-onna',
    'Наха → Онна → аэропорт',
    '25 и 28 октября',
    'Окинава',
    yen(5600),
    'Two Ride Pass: по ¥2 800 на два переезда. Остановка Kariyushi Beach. Место в автобусе не резервируется; проверить рейс к самолёту.',
    'https://www.okinawa-shuttle.co.jp/en/good-value/',
  ),
  travel(
    't-kerama',
    'Токасики: паром и автобус к пляжу',
    '24 октября',
    'Острова Керама',
    yen(14340),
    'На двоих: Marine Liner туда-обратно ¥12 540, экологический сбор ¥200, автобус до Aharen и обратно ¥1 600. Паром зависит от погоды. Тариф парома действует с 1 октября 2026.',
    'https://tokashiki-ferry.jp/Senpaku/portal',
  ),
  travel(
    't-aquarium',
    'Онна → Churaumi → Онна',
    '26 октября',
    'Окинава',
    2700,
    'Резерв на автобус туда-обратно на двоих. Сверить остановки и расписание; это не цена брони.',
    'https://www.okinawa-shuttle.co.jp/en/timetable/',
    'budget',
  ),
  travel(
    't-naha-local',
    'Поездки по Нахе',
    '22–25 октября',
    'Наха',
    2000,
    'Резерв на монорельс и автобусы на двоих. Паром и аэропорт учтены отдельно.',
    'https://www.yui-rail.co.jp/',
    'budget',
  ),
  travel(
    't-kix',
    'Кансай → отель в Осаке',
    '28 октября',
    'Осака',
    1400,
    'Резерв на обычный поезд Nankai и городской участок. Из T2 сначала бесплатный автобус к Aeroplaza.',
    'https://www.nankai.co.jp/en_railway/access-timetable',
    'budget',
  ),
  travel(
    't-kyoto',
    'Осака → Киото',
    '1 ноября',
    'Киото',
    yen(820),
    'Hankyu Osaka-Umeda → Kyoto-Kawaramachi: по ¥410. Дорога от/до отелей — в городском резерве.',
    'https://enjoy-osaka-kyoto-kobe.com/article/a/kyo-train-garaku-interior-design/',
  ),
  travel(
    't-nara',
    'Осака → Нара → Осака',
    '30 октября',
    'Нара',
    yen(2720),
    'Обычный поезд Kintetsu от Osaka-Namba: расчёт по ¥680 в одну сторону на человека. Без доплаты за limited express.',
    'https://www.kintetsu.co.jp/foreign/english/',
  ),
  travel(
    't-usj',
    'Осака → Universal → Осака',
    '29 октября',
    'Осака',
    yen(800),
    'JR от Osaka Station: расчёт по ¥200 в сторону на человека. До станции — из городского резерва.',
    'https://www.usj.co.jp/web/ja/jp/access/train',
  ),
  travel(
    't-naruto',
    'Осака → парк Наруто → Осака',
    '31 октября',
    'Авадзи',
    yen(7400),
    'Автобус: по ¥1 850 в сторону на человека. Выбирать остановку Nijigen no Mori и сверить обратный рейс.',
    'https://timetable.nishinihonjrbus.co.jp/faretable/5-1-D.html',
  ),
  travel(
    't-osaka-local',
    'Городской транспорт Осаки',
    '28 октября — 1 ноября',
    'Осака',
    yen(4800),
    'Резерв: ¥600 на человека в день × 4 дня. Межгород, аэропорт и поезд к Universal вынесены отдельно.',
    'https://subway.osakametro.co.jp/en/',
    'budget',
  ),
  travel(
    't-kyoto-local',
    'Городской транспорт Киото',
    '1–5 ноября',
    'Киото',
    yen(6400),
    'Резерв: ¥800 на человека в день × 4 дня. Пешие прогулки и группировка мест по районам помогают уложиться.',
    'https://www2.city.kyoto.lg.jp/kotsu/webguide/en/bus/howtoride_bus.html',
    'budget',
  ),
  travel(
    't-shinkansen',
    'Киото → Мисима · синкансэн',
    '5 ноября',
    'К Фудзи',
    yen(22220),
    'По ¥11 110, Hikari / Kodama, обычный класс с местом. Расчёт по тарифу Smart EX; на Trip.com итог может отличаться.',
    'https://www.trip.com/trains/japan/',
  ),
  travel(
    't-mishima',
    'Мисима → Кавагутико',
    '5 ноября',
    'Фудзи',
    yen(5400),
    'Автобус: по ¥2 700. Онлайн бывает ¥2 500, скидку пока не вычитаем. Заложить время на пересадку.',
    'https://www.fujikyucitybus.com/highwaybus/kawaguchiko.html',
  ),
  travel(
    't-fuji-local',
    'Озеро и поездка в Yurari',
    '5–6 ноября',
    'Фудзи',
    2000,
    'Резерв на местные автобусы на двоих. Если подходит бесплатный трансфер онсэна, расходы будут ниже.',
    'https://www.fuji-yurari.jp/',
    'budget',
  ),
  travel(
    't-tokyo',
    'Кавагутико → Синдзюку',
    '6 ноября',
    'Токио',
    yen(4400),
    'Автобус: по ¥2 200. На сайте перевозчика возможен веб-тариф ¥2 000; ноябрьскую цену уточнять при покупке.',
    'https://bus.fujikyu.co.jp/en/highway/fujisan/shinjuku-kawaguchiko/',
  ),
  travel(
    't-tokyo-local',
    'Транспорт Токио · 72 часа + доплаты',
    '6–10 ноября',
    'Токио',
    3320,
    'Включает Tokyo Subway Ticket по ¥2 000 на 72 часа и резерв на JR / участки вне действия билета. Ещё раз отдельно проездной в бюджет не добавлять.',
    'https://us.trip.com/things-to-do/detail/24465457?language=EN&locale=en_us',
    'budget',
  ),
  travel(
    't-narita',
    'Отель → аэропорт Нарита',
    '10 ноября',
    'Токио',
    1660,
    'Резерв на обычный поезд Keisei / Toei и подводящий участок. Без дорогого Skyliner.',
    'https://www.keisei.co.jp/keisei/tetudou/skyliner/us/traffic/main_fares.php',
    'budget',
  ),
  travel(
    't-reserve',
    'Запас на такси и смену планов',
    'Вся поездка',
    'Все города',
    4500,
    'Общий резерв, а не заранее купленный проезд. Для позднего заселения, дождя или неудобной стыковки автобусов.',
    undefined,
    'budget',
  ),
  place(
    'p-usj',
    'Universal Studios Japan · 1 день',
    '29 октября',
    'Осака',
    19800,
    'По ¥9 900 по календарю USJ на 29 октября. Без Express Pass. Для Super Nintendo World может понадобиться отдельный вход по времени; доступ не гарантирован.',
    'https://us.trip.com/travel-guide/attraction/osaka/universal-studios-japan-81012/',
    {
      label: 'Официальный календарь USJ',
      url: 'https://www.usjticketing.com/',
    },
  ),
  place(
    'p-naruto',
    'NARUTO & BORUTO Shinobi-Zato · Light',
    '31 октября',
    'Авадзи',
    8200,
    'Резерв по верхней границе Light: ¥3 300–4 100 на взрослого. Цена зависит от дня. Билеты — по кнопке на официальном сайте, через Asoview.',
    'https://www.nijigennomori.com/en/naruto_shinobizato/',
  ),
  place(
    'p-churaumi',
    'Океанариум Churaumi',
    '26 октября',
    'Окинава',
    4360,
    'По ¥2 180 на взрослого, обычный официальный тариф. Trip.com может предложить другую итоговую цену. Пляж Emerald рядом — бесплатный.',
    'https://us.trip.com/travel-guide/attraction/motobu/okinawa-churaumi-aquarium-10559035/',
    { label: 'Официальный сайт', url: 'https://churaumi.okinawa/en/' },
  ),
  place(
    'p-yurari',
    'Онсэн Fuji Yurari',
    '5 ноября',
    'Фудзи',
    2800,
    'Будний день: по ¥1 400, полотенца включены. Общие раздельные купальни; татуировки запрещены правилами. Оплата на месте.',
    'https://www.fuji-yurari.jp/charge-plan.html',
  ),
  place(
    'p-sky',
    'Shibuya Sky · дневной вход',
    '8 ноября',
    'Токио',
    5400,
    'Онлайн до 14:59: по ¥2 700; с 15:00 — дороже. Продажи открываются за две недели: на ноябрь пока не купить. Проверить слот и погоду.',
    'https://us.trip.com/travel-guide/attraction/tokyo/shibuya-sky-136018827/',
    {
      label: 'Официальные билеты',
      url: 'https://shibuya-scramble-square.com/sky/ticket/',
    },
  ),
  place(
    'p-kinkaku',
    'Кинкакудзи',
    '2 ноября',
    'Киото',
    1000,
    'По ¥500 на взрослого. Билеты на месте.',
    'https://www.shokoku-ji.jp/kinkakuji/access/',
  ),
  place(
    'p-todaiji',
    'Тодайдзи · зал Большого Будды',
    '30 октября',
    'Нара',
    1600,
    'По ¥800. Парк Нары и прогулка с оленями — бесплатно; корм отдельно по желанию.',
    'https://www.todaiji.or.jp/information/haikan/',
  ),
  place(
    'p-tenryu',
    'Тэнрюдзи · сад',
    '2 ноября',
    'Киото',
    1000,
    'По ¥500, только сад. Посещение зданий — за доплату. Бамбуковая роща Арасиямы бесплатна.',
    'https://www.tenryuji.com/en/visit/index.html',
  ),
  {
    id: 'p-kiyomizu',
    category: 'place',
    title: 'Киёмидзу-дэра',
    date: '4 ноября',
    city: 'Киото',
    price: 600,
    kind: 'budget',
    note: 'Резерв на обычный вход на двоих. Вечерние специальные сеансы могут иметь отдельный тариф.',
    link: 'https://www.kiyomizudera.or.jp/en/visit/',
    linkLabel: 'Часы и посещение',
  },
  {
    id: 'p-nijo',
    category: 'place',
    title: 'Замок Нидзё · по желанию',
    date: '3 ноября',
    city: 'Киото',
    price: 1500,
    kind: 'budget',
    note: 'Резерв на двоих, набор доступных дворцов влияет на цену. Если решите пропустить — измените план на 0 ₽.',
    link: 'https://nijo-jocastle.city.kyoto.lg.jp/admission/ticket/?lang=en',
    linkLabel: 'Выбрать посещение',
  },
  {
    id: 'p-naha',
    category: 'place',
    title: 'Сюри и Тамаудун',
    date: '23 октября',
    city: 'Наха',
    price: 1000,
    kind: 'budget',
    note: 'Резерв на платные зоны на двоих. Главный зал Сюри открывается только 23 ноября 2026; в октябре — парк и доступные участки.',
    link: 'https://oki-park.jp/shurijo/en/',
    linkLabel: 'Что открыто',
  },
  {
    id: 'p-small',
    category: 'place',
    title: 'Небольшие входные билеты у Фудзи',
    date: '5–6 ноября',
    city: 'Фудзи',
    price: 1500,
    kind: 'budget',
    note: 'Необязательный резерв: смотровая, небольшая выставка или другой платный объект по погоде. Конкретный билет ещё не выбран.',
  },
  {
    id: 'd-food',
    category: 'daily',
    title: 'Еда в Японии',
    date: '22 октября — 10 ноября',
    city: '20 календарных дней',
    price: 50000,
    kind: 'budget',
    note: 'Экономный план: около 2 500 ₽ на двоих в день, простые кафе, завтраки и комбини. Во вкладке «Где дешевле» можно поднять бюджет до 65 000 ₽. Дорогие рестораны и регулярный алкоголь не заложены.',
  },
  {
    id: 'd-transit',
    category: 'daily',
    title: 'Еда во время пересадок',
    date: '20–22 октября и 10–12 ноября',
    city: 'Ханчжоу · Гонконг · Доха',
    price: 6500,
    kind: 'budget',
    note: 'Резерв на двоих на длинную дорогу. Бесплатное питание авиакомпаний не считается отдельным расходом.',
  },
  {
    id: 'd-tax',
    category: 'daily',
    title: 'Местные сборы отелей',
    date: 'Вся поездка',
    city: 'Япония',
    price: 2500,
    kind: 'budget',
    note: 'Запас на сборы, которые могут оплачиваться в отеле. Не оплачивайте повторно то, что уже включено в ваучер; скорректируйте после бронирования.',
  },
);
export const stops = [
  {
    name: 'Наха',
    date: '22–25 окт.',
    nights: '3 ночи',
    text: 'Город, Сюри и один день на Токасики.',
  },
  {
    name: 'Онна',
    date: '25–28 окт.',
    nights: '3 ночи',
    text: 'Пляж, море и океанариум Churaumi.',
  },
  {
    name: 'Осака',
    date: '28 окт. — 1 нояб.',
    nights: '4 ночи',
    text: 'Universal, Нара и парк Наруто.',
  },
  {
    name: 'Киото',
    date: '1–5 нояб.',
    nights: '4 ночи',
    text: 'Храмы, Гион и Арасияма без спешки.',
  },
  {
    name: 'Фудзи',
    date: '5–6 нояб.',
    nights: '1 ночь',
    text: 'Кавагутико и онсэн с видом на гору.',
  },
  {
    name: 'Токио',
    date: '6–10 нояб.',
    nights: '4 ночи',
    text: 'Три полных дня в городе и вылет вечером 10 ноября.',
  },
];
export const kindLabels = {
  quote: 'Цена проверки',
  tariff: 'Тариф / расчёт',
  budget: 'Резерв бюджета',
};
